# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/sgmt.sh/git/ccompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/sgmt.sh/git/ccompiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sgmt.sh/git/ccompiler/CMakeFiles /mnt/c/Users/sgmt.sh/git/ccompiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sgmt.sh/git/ccompiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ccompiler

# Build rule for target.
ccompiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ccompiler
.PHONY : ccompiler

# fast build rule for target.
ccompiler/fast:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/build
.PHONY : ccompiler/fast

codegen.o: codegen.c.o

.PHONY : codegen.o

# target to build an object file
codegen.c.o:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/codegen.c.o
.PHONY : codegen.c.o

codegen.i: codegen.c.i

.PHONY : codegen.i

# target to preprocess a source file
codegen.c.i:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/codegen.c.i
.PHONY : codegen.c.i

codegen.s: codegen.c.s

.PHONY : codegen.s

# target to generate assembly for a file
codegen.c.s:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/codegen.c.s
.PHONY : codegen.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/main.c.s
.PHONY : main.c.s

parse.o: parse.c.o

.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i

.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s

.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/parse.c.s
.PHONY : parse.c.s

tokenize.o: tokenize.c.o

.PHONY : tokenize.o

# target to build an object file
tokenize.c.o:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/tokenize.c.o
.PHONY : tokenize.c.o

tokenize.i: tokenize.c.i

.PHONY : tokenize.i

# target to preprocess a source file
tokenize.c.i:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/tokenize.c.i
.PHONY : tokenize.c.i

tokenize.s: tokenize.c.s

.PHONY : tokenize.s

# target to generate assembly for a file
tokenize.c.s:
	$(MAKE) -f CMakeFiles/ccompiler.dir/build.make CMakeFiles/ccompiler.dir/tokenize.c.s
.PHONY : tokenize.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ccompiler"
	@echo "... edit_cache"
	@echo "... codegen.o"
	@echo "... codegen.i"
	@echo "... codegen.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... tokenize.o"
	@echo "... tokenize.i"
	@echo "... tokenize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

